# Generated by Django 3.1.1 on 2020-10-09 06:50

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201006_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
