# Generated by Django 3.1.1 on 2020-11-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201013_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_at',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='date',
            new_name='date_at',
        ),
        migrations.RenameField(
            model_name='reviewpost',
            old_name='date',
            new_name='date_at',
        ),
    ]
