# Generated by Django 3.1.1 on 2020-11-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201013_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='date_at',
        ),
        migrations.RenameField(
            model_name='newscomment',
            old_name='date',
            new_name='date_at',
        ),
    ]
