# Generated by Django 3.1.1 on 2020-10-07 06:57

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201007_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
    ]
