# Generated by Django 3.1.1 on 2020-11-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201019_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
