# Generated by Django 3.1.1 on 2020-10-09 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20201006_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='user',
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
